# Java异常处理

## 层次

![exception类的层次](https://www.runoob.com/wp-content/uploads/2013/12/12-130Q1234I6223.jpg)



## Error

Error一般表示编译时或者系统错误，例如，虚拟机相关的错误，系统崩溃等。这种错误无法恢复或不可捕获，将导致应用程序终端，通常应用程序无法处理这些错误，因此也不应该试图通过**catch**来进行捕获。

## Exception

Java中的异常分为**受检异常(checked exception)**和**非受检异常(unchecked exception)**。

### 受检异常

受检异常是指必须使用**try-catch**语句块包起来或者使用**throw-throws**抛出的异常，否则将不会通过编译。

### 非受检异常

此类异常通常也称为运行时异常。



## 异常处理

### 捕获

```java
try{
    ///可能会抛出异常的代码
}catch(Exp1 e1){
    //处理Type1类型异常的代码
}catch(Exp2 e2){
    //处理Type2类型异常的代码
}
```

上面代码是个简单的例子，其中Exp1不能是Exp2以及后面一些异常类型的父类，简而言之，排在前面的类型范围窄，后面可以更宽。另外，就算catch没有捕获到，虚拟机还是会捕获到的。

### 抛出

```java
public void f() throws ClassNotFoundException,IOException{}
```

这样我们调用f()方法的时候必须要catch-**ClassNotFoundException**和**IOException**这两个异常或者catch-**Exception**基类。
 注意：
 throws的这种使用方式只是Java编译期要求我们这样做的，我们完全可以只在方法声明中throws相关异常，但是在方法里面却不抛出任何异常，这样也能通过编译，我们通过这种方式间接的绕过了Java编译期的检查。这种方式有一个好处：为异常先占一个位置，以后就可以抛出这种异常而不需要修改已有的代码。在定义抽象类和接口的时候这种设计很重要，这样派生类或者接口实现就可以抛出这些预先声明的异常。

注意**throw**与**throws**的区别，**throws**是用在方法定义处，可以抛出多种异常，**throw**是用于在方法体中，后面紧跟所要抛出的异常，每次**throw**只能一种**Exception**。

**构造方法不应该抛出非受检异常。**

### finally

通常，无论异常是否发生，**finally**语句都是会执行的。另外还需要注意**finally**语句块中对返回值的影响。

```java
    public static int testException(){
        int AA = 10;
        try {
            AA = 11;
            int a = 10/0;
            return AA;
        } catch (ArithmeticException e) {
            AA = 12;
            return AA;
        } finally {
            AA = 13;
            // return AA;
        }
    }
```

上面代码中，testException的返回值会是12，而不是13。但是如果把注释去掉，则返回值才是13。说明**finally**语句块确实执行了，但是对所要返回的变量的赋值不影响其返回值（其实**finally**中的变量**AA**是副本），而且**finally**中对返回值可有可无。

### 返回值问题

**try**块中依次执行，如果没有发生异常，则运行到返回值处或者是异常抛出处停止。如果有异常，则马上离开**try**块（剩下内容将得不到执行），跳到相应的**catch**块中执行完相应的逻辑。每个逻辑分支必须确保有结束点。**不管任何情况，根据相应逻辑顺序执行，遇到返回值或者异常抛出方法就运行结束。**

### try-with-resources

try-with-resources 是 JDK 7 中一个新的异常处理机制，它能够很容易地关闭在 try-catch 语句块中使用的资源。所谓的资源（resource）是指在程序完成后，必须关闭的对象。try-with-resources 语句确保了每个资源在语句结束时关闭。所有实现了 **[java.lang.AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) **接口（其中，它包括实现了**[java.io.Closeable](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html) **的所有对象），可以使用作为资源。try中可以声明多种资源，使用完后会自动调用**close**方法来关闭。如下列代码：

```java
    static class ResourceOne implements AutoCloseable {

        public void doThing() {
            System.out.println("使用资源1");
        }

        @Override
        public void close() throws Exception {
            System.out.println("资源1释放了");
        }
    }

    static class ResourceTwo implements AutoCloseable {

        public void doThing() {
            System.out.println("使用资源2");
        }

        @Override
        public void close() throws Exception {
            System.out.println("资源2释放了");
        }
    }

    public static void testWithResource() {
        ResourceOne resourceOne = new ResourceOne();
        ResourceTwo resourceTwo = new ResourceTwo();

        try(resourceOne;resourceTwo) {
            resourceOne.doThing();
            resourceTwo.doThing();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            System.out.println("资源调用完毕");
        }
    }

    public static void main(String[] args) {
        testWithResource();
    }
```

输出结果为：

```java
使用资源1
使用资源2
资源2释放了
资源1释放了
资源调用完毕
```

可以看出，在调用资源的**close**方法后再调用的**finally**方法。而且释放资源的顺序与声明的顺序**相反**。

#### **try-with-resources**在**JDK9**中的改进

如果某种资源对象已经存在了，则只需要在**try**块声明中加上资源对象的名称即可，如上例。



## 自定义异常类

可以通过继承**java.lang.Exception**类来实现自定义类。



## API链接

JDK11版

[java.lang.Throwable](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Throwable.html)

[java.lang.Error](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Error.html)

[java.lang.Exception](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Exception.html)



